### ISSUE TITLE
Request: AIO - Add battery temperature and voltage

### ISSUE THREAD

**Issue by blastehh** [britkat1980/giv_tcp#161]
I had a look at the REST output and under raw.inverter there is `temp_battery` and `v_battery` available, can these be added so HA can see them?
Would it also be possible to send the inverter temp, battery temp, and battery voltage to influxdb?

**Comment by blastehh** [comment]
Attaching my output for reference
[aio-rest.json](https://github.com/britkat1980/giv_tcp/files/13752473/aio-rest.json)

**Comment by 7Van737** [comment]
And following the same logic here is the code for the battery voltage which appears to work.  

sensor:
  - name: "AIO BMS Temp"
    unique_id: aio-bms-temp
    state_topic: "Givenergy/CHXXXXXX/raw/invertor/temp_battery"
    device_class: Temperature
    unit_of_measurement: "°C"
    state_class: measurement
    icon: "mdi:thermometer"

  - name: "AIO Voltage"
    unique_id: aio-voltage
    state_topic: "Givenergy/CHXXXXXX/raw/invertor/v_battery"
    device_class: Voltage
    unit_of_measurement: "V"
    state_class: measurement

**Comment by PianSom** [comment]
Thanks for the hints. For me to get this to work I have to have the capital E in GivEnergy

**Comment by PianSom** [comment]
Actually - this is a nice solution: https://github.com/Codegnosis/givtcp-battery-card

**Comment by PianSom** [comment]
Deleted the comment, because it doesn't have either voltage or temperature! Oops

**Comment by blastehh** [comment]
> Here is the code I found on a GE facebook thread that creates the Battery Temperature as an entity. Works for me.
> 
> sensor:
> 
>     * name: "AIO BMS Temp"
>       unique_id: aio-bms-temp
>       state_topic: "Givenergy/CHXXXXXXXX/raw/invertor/temp_battery"
>       device_class: Temperature
>       unit_of_measurement: "°C"
>       state_class: measurement
>       icon: "mdi:thermometer"
> 
> 
> Created a new file called mqtt.yaml in the config folder with 'mqtt: !include mqtt.yaml' added to the configeration.yaml

this is perfect, thanks.

for those who want to copy:
```
sensor:
  - name: "AIO BMS Temp"
    unique_id: aio-bms-temp
    state_topic: "Givenergy/CHXXXXXX/raw/invertor/temp_battery"
    device_class: Temperature
    unit_of_measurement: "°C"
    state_class: measurement
    icon: "mdi:thermometer"

  - name: "AIO BMS Temp"
    unique_id: aio-bms-temp
    state_topic: "Givenergy/CHXXXXXX/raw/invertor/temp_battery"
    device_class: Temperature
    unit_of_measurement: "°C"
    state_class: measurement
    icon: "mdi:thermometer"

  - name: "AIO Voltage"
    unique_id: aio-voltage
    state_topic: "Givenergy/CHXXXXXX/raw/invertor/v_battery"
    device_class: Voltage
    unit_of_measurement: "V"
    state_class: measurement

```
