### ISSUE TITLE
Which service to set a timeslot?

### ISSUE THREAD

**Issue by yavinmaster** [britkat1980/giv_tcp#172]
How do you set a timeslot to a time in a HomeAssistant automation?  Is it a service call, if so which one?

Sorry for the fundamental question but for some reason I just can't find a solution.

**Comment by gcoan** [comment]
> How do you set a timeslot to a time in a HomeAssistant automation?  Is it a service call, if so which one?
> 
> 
> 
> Sorry for the fundamental question but for some reason I just can't find a solution.

If I have understood you correctly, you are trying to set a time such as charge/discharge start/end time.

This is how I do it in my scripts:

```
  - service: select.select_option
    data:
      option: "00:00:00"
    target:
      entity_id:
        - select.givtcp_SERIALNO_discharge_start_time_slot_1
  - service: select.select_option
    data:
      option: "23:59:00"
    target:
      entity_id: select.givtcp_SERIALNO_discharge_end_time_slot_1
```
