### ISSUE TITLE
Set value for "GivTCP Control GivTCP Target SOC" using a parameter

### ISSUE THREAD

**Issue by BobB001** [britkat1980/giv_tcp#247]
Hi folks,
<TL;DR>
Is it possible to pass the value of a variable to GivTCP SAnnnnGnnn Control GivTCP Target SOC?

Background:
I'm using Home Assistant and GivTCP v2.4.9.
My inverter does not always accept a control command the first time it is issued, so I end up surrounding all commands with a while loop, something like:
```
While the setting isn't what you want
  Request the new setting
  Wait a bit
End While
```
This is a bit tedious to copy everywhere, so I'd like to set up a script to do the loop and call it with a parameter of the actual value.
Something like this:
```
alias: Set Givenergy Battery target SOC
sequence:
  - repeat:
      sequence:
        - delay:
            hours: 0
            minutes: 0
            seconds: 30
            milliseconds: 0
        - device_id: xxx
          domain: number
          entity_id: xxx
          type: set_value
          value: {{ target_soc }}
      while:
        - condition: not
          conditions:
            - condition: template
              value_template: >-
                {{states("number.givtcp_sa2237g056_target_soc") | int ==
                target_soc}}
```

...where target_soc is a field passed into the script.
But I can't get this to work. It's as if the Control GivTCP Target SOC device action is checking specifically for a number.

Do any of you brainboxes know how I might do this? Or is it a lost cause? My second option is to write several scripts each with a hard-coded value, so have a Set_SOC_50, Set_SOC_60, Set_SOC_80 etc.

Thanks in advance.
